# Generated by Django 5.0.6 on 2024-07-25 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_app', '0005_usertype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
