# Generated by Django 5.0.6 on 2024-08-07 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_app', '0009_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='days_of_week',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='max_slots',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='min_slots',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='weekend_days',
            field=models.JSONField(default=list),
        ),
    ]
